### ISSUE TITLE
subtitle not showing on some channels 

### ISSUE THREAD

**Issue by medousa89** [opendroid-Team/enigma2#19]
According to the spec object_vertical_position is not a 16 bitfield. First 4 bits are reserved for future use.
and need this `object->object_vertical_position  = (*segment++ & 0xF) << 8;`
https://github.com/opendroid-Team/enigma2/blob/72e4ecfba7cc11212d0beb0093faf9bae7613127/lib/dvb/subtitle.cpp#L508

**Comment by opendroid-Team** [comment]
https://github.com/opendroid-Team/enigma2/blob/5c73a2ac6f49d7d899992de485ae5e816473696e/lib/dvb/subtitle.cpp#L508
