### ISSUE TITLE
Problem when changing language 

### ISSUE THREAD

**Issue by elhawaryna** [opendroid-Team/enigma2#33]
Hello
when you choose English or a language other than Italian, this error occurs 
[enigma2_crash_1638617821.log](https://github.com/opendroid-Team/enigma2/files/7653858/enigma2_crash_1638617821.log)

*****************************
OpenDroid Enigma2 crash log

crashdate=sab dic  4 12:37:01 2021
compiledate=Dec  4 2021
skin=OPD-Blue-Line/skin.xml
sourcedate=2021-12-03
branch=7.1
rev=a71256c
component=Enigma2

stbmodel=ultimo
stbmodel=dm820
kernelcmdline=bmem=512M@512M memc1=768M console=ttyS0,1000000 root=/dev/mmcblk0p1 rootwait rootfstype=ext4
nimsockets=NIM Socket 0:
imageversion=box_type=dm820
imageissue=Welcome to opendroid for %h

12:36:36.5511 [Enigma] Python path is '/usr/lib/enigma2/python'.
12:36:36.5515 [Enigma] DVB API version 5, DVB API version minor 11.
12:36:36.5515 [Enigma] Enigma debug level 3.
12:37:01.0466 [ePyObject] (PyObject_CallObject(<bound method Navigation.dispatchEvent of <Navigation.Navigation object at 0x6f451c40>>,(0,)) failed)

dmesg

<4>[ 1745.545000] stop PCR0 on dmx 0 pid:13f7
<4>[ 1745.546000] stop AUDIO0 on dmx 0 pid:13f8
<4>[ 1745.546000] audio ch0: xpt stop
<4>[ 1745.547000] audio ch0: decoder stop
<6>[ 1745.563000] bcm4506: channel 0 is sleeping now
<4>[ 1745.567000] stop VIDEO0 on dmx 0 pid:13f7
<4>[ 1745.568000] VIDEO0: stop decode
<4>[ 1745.568000] sync0 1fff no decoder left in sync handling so disable
<4>[ 1745.569000] sync0: was last pcroffset0 user so free it
<4>[ 1746.612000] VIDEO0: set streamtype!
<4>[ 1746.612000] ->      set MPEG2
<4>[ 1746.613000] ->      sw rave disabled!
<4>[ 1746.614000] sync0 is off so we enable it
<4>[ 1746.614000] sync0: allocated pcroffset 0
<4>[ 1746.615000] sync0: playback!
<4>[ 1746.615000] VIDEO0: total delay: 0 (0 ms)
<4>[ 1746.620000] VIDEO0: start decode
<4>[ 1746.621000] VIDEO0: flush video decoder
<4>[ 1746.621000] VIDEO0 use saved pts 0x5cf8bc38 (ret 0)
<4>[ 1746.678000] VIDEO0: first pts 0x0
<4>[ 1746.678000] VIDEO0: framerate changed 3
<4>[ 1746.679000] set current avs auto aspect to 16:9
<4>[ 1746.680000] set sb to 3(1)
<4>[ 1746.830000] VIDEO0: enable tsm
<4>[ 1746.901000] VIDEO0: stop decode
<4>[ 1746.901000] sync0 1fff no decoder left in sync handling so disable
<4>[ 1746.902000] sync0: was last pcroffset0 user so free it
<3>[ 1747.122000] bcm_accel: invalid opcode! 00000080
<6>[ 1747.124000] bcmfb: creating surface with pixel format 0x07e48888 (BPXL_eA8_R8_G8_B8)
<4>[ 1747.451000] HDMI: CEC device open ... state is 3, flushed 0 old messages from RX fifo
<4>[ 1747.452000] HDMI: CEC returned state 3
<4>[ 1747.453000] HDMI: CEC state now 803
<4>[ 1747.580000] HDMI: CEC send ok!
<6>[ 1747.615000] bcm4506: channel 0 is in normal mode now
<6>[ 1747.627000] bcm4506: channel 0 is sleeping now
<4>[ 1747.652000] VIDEO0: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[ 1747.653000] set current avs auto aspect to 16:9
<4>[ 1747.654000] set sb to 3(1)
<4>[ 1747.654000] VIDEO1: dst_left, dst_top, dst_width and dst_height is 0.. reset to defaults!
<4>[ 1748.171000] 244817 ms: 74 
<4>[ 1748.216000] 44 ms: 50 
<4>[ 1749.794000] 1578 ms: 64 
<4>[ 1752.690000] 2895 ms: 53 
<4>[ 1752.759000] 69 ms: 68 
<4>[ 1752.787000] 28 ms: 59 
<4>[ 1753.043000] 256 ms: 59 
<4>[ 1754.080000] 1037 ms: 60 
<4>[ 1754.145000] 64 ms: 62 
<4>[ 1754.146000] 1 ms: 62 
<4>[ 1754.156000] 10 ms: 62 
<4>[ 1754.157000] 1 ms: 62 
<4>[ 1754.158000] 1 ms: 62 
<4>[ 1754.177000] 19 ms: 62 
<4>[ 1754.276000] 99 ms: 62 
<4>[ 1754.282000] 6 ms: 62 
<4>[ 1754.301000] 18 ms: 62 
<4>[ 1754.302000] 1 ms: 62 
<4>[ 1754.393000] 90 ms: 62 
<4>[ 1754.394000] 1 ms: 62 
<4>[ 1754.401000] 7 ms: 62 
<4>[ 1755.056000] 655 ms: 62 
<4>[ 1755.082000] 25 ms: 64 
<4>[ 1755.092000] 10 ms: 64 
<4>[ 1755.093000] 1 ms: 64 
<4>[ 1755.096000] 3 ms: 64 
<4>[ 1755.104000] 8 ms: 64 
<4>[ 1755.105000] 1 ms: 64 
<4>[ 1755.155000] 49 ms: 64 
<4>[ 1755.186000] 31 ms: 64 
<4>[ 1755.188000] 1 ms: 64 
<4>[ 1755.189000] 1 ms: 64 
<4>[ 1755.193000] 3 ms: 64 
<4>[ 1755.203000] 10 ms: 64 
<4>[ 1755.204000] 1 ms: 64 
<4>[ 1755.210000] 5 ms: 64 
<4>[ 1756.416000] 1206 ms: 64 
<4>[ 1756.456000] 40 ms: 68 
<4>[ 1756.485000] 28 ms: 68 
<4>[ 1756.511000] set current avs auto aspect to 16:9
<4>[ 1756.511000] set sb to 3(1)
<4>[ 1756.514000] set current avs auto aspect to 16:9
<4>[ 1756.515000] set sb to 3(1)
<4>[ 1756.517000] set current avs auto aspect to 16:9
<4>[ 1756.517000] set sb to 3(1)
<4>[ 1756.519000] set input to 0
<4>[ 1756.519000] set fb to 2(-1)
<4>[ 1756.519000] set current avs auto aspect to 16:9
<4>[ 1756.520000] set sb to 3(1)
<4>[ 1756.538000] set mute 0 0
<4>[ 1756.540000] set ac3 to downmix
<4>[ 1756.542000] set ac3plus to force_ac3
<4>[ 1756.543000] set dtshd to use_hdmi_caps
<4>[ 1756.545000] set wmapro to downmix
<4>[ 1756.547000] set aac to downmix
<4>[ 1756.583000] set current avs auto aspect to 16:9
<4>[ 1756.584000] set sb to 3(1)
<4>[ 1756.585000] set current avs auto aspect to 16:9
<4>[ 1756.585000] set sb to 3(1)
<4>[ 1756.589000] 104 ms: 68 
<4>[ 1756.593000] 4 ms: 68 
<4>[ 1756.604000] 10 ms: 68 
<4>[ 1757.289000] 684 ms: 68 
<4>[ 1757.494000] 204 ms: 69 
<4>[ 1757.596000] 102 ms: 70 
<4>[ 1757.600000] 4 ms: 70 
<4>[ 1757.816000] 216 ms: 70 
<4>[ 1757.836000] 20 ms: 70 
<4>[ 1758.131000] set current avs auto aspect to 16:9
<4>[ 1758.132000] set sb to 3(1)
<4>[ 1758.133000] set current avs auto aspect to 16:9
<4>[ 1758.134000] set sb to 3(1)
<4>[ 1758.135000] set current avs auto aspect to 16:9
<4>[ 1758.136000] set sb to 3(1)
<4>[ 1758.137000] set current avs auto aspect to 16:9
<4>[ 1758.138000] set sb to 3(1)
<4>[ 1765.128000] using 50.00Hz as MonitorRefreshRate
<4>[ 1765.128000] VIDEO1: shared window not available
<4>[ 1765.208000] SET FORMAT: display[0], format='720p50'
<4>[ 1765.208000] HDMI mode
<4>[ 1765.209000] use EDID to detect colorspace
<4>[ 1765.209000] preferred colorspace: Itu_R_BT_709
<4>[ 1765.308000] VIDEO1: shared window not available
<4>[ 1765.388000] set current avs auto aspect to 16:9
<4>[ 1765.388000] set sb to 3(1)
<4>[ 1771.201000] rtc set to 1638617820
<4>[ 1771.203000] rtc set to valid now

**Comment by opendroid-Team** [comment]
fix https://github.com/opendroid-Team/enigma2/commit/42d7d9cd2aaa1f9dce9793a3b92084d1f182ee3b
Thanks...
