### ISSUE TITLE
Optibox Evo Xfinity XMBC

### ISSUE THREAD

**Issue by jasmin811** [opendroid-Team/enigma2#8]
Hello there,
How can I install latest opendroid 6 on this box,I have currently opendroid 5.3.

The file for opendroid 5.3 image on this box looks like this: rootfs.tar.bz2, bootargs.img, fastboot.img, kernel.img, logo.img, part.img, recovery.img

I'm just wonder if it is possible?

The box it's like that one:

**Comment by jasmin811** [comment]
Anyone??

**Comment by opendroid-Team** [comment]
I'm sorry we do not develop for this box
regards
